# Change these first
owner: GiuseppeFilingeri # Your GitHub organization or username, where this repository lives
repo: upgraded-symmetrical-waddle  # The name of this repository 

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Disdicilo
    url: https://www.disdicilo.it
  - name: Mangahype
    url: https://www.mangahype.org
  - name: DuckDuckGo
    url: https://duckduckgo.com
  - name: symmetrical waddle
    url: https://giuseppefilingeri.github.io/upgraded-symmetrical-waddle
  - name: ziggys-bar
    url: ziggys-bar.com
  - name: nedis
    url: nedis.nl
  - name: websearch
    url: websearch.com
  - name: iranrapfa
    url: iranrapfa.com
  - name: allekabels
    url: allekabels.nl
  - name: kabeltje
    url: kabeltje.com
  - name: cocinasana
    url: cocinasana.net
  - name: bitfan
    url: bitfan.com
  - name: xxlhd
    url: xxlhd.com
  - name: megachicks
    url: megachicks.ru
  - name: riphone
    url: riphone.ru
  - name: riphone
    url: riphone.ru
  - name: twoc
    url: twoc.co.uk
  - name: btinternet
    url: btinternet.com
  - name: cryo-save
    url: cryo-save.com
  - name: funniegames
    url: funniegames.nl
  - name: hcr
    url: hcr.co.uk
  - name: hcr
    url: hcr.com
  - name: kazeebo
    url: kazeebo.com
  - name: bluewin
    url: bluewin.com
  - name: emilcohen
    url: emilcohen.com
  - name: freeusweb
    url: freeusweb.com
  - name: urbanlime
    url: urbanlime.com
  - name: smartcine
    url: smartcine.com
  - name: bizline
    url: bizline.com.pk
  - name: alkon
    url: alkon.com.ar
  - name: alkon
    url: alkon.com.ar
  - name: inkmizer
    url: inkmizer.com
  - name: inkcityusa
    url: inkcityusa.com
  - name: inkcityusa
    url: inkcityusa.com
  - name: ajexa
    url: ajexa.com
  - name: everbesthk
    url: everbesthk.com
  - name: hongkong
    url: hongkong.com
  - name: hket
    url: hket.com
  - name: raoiit
    url: raoiit.com
  - name: citybuild
    url: citybuild.bg
  - name: phun
    url: phun.org
  - name: anyoption
    url: anyoption.com
  - name: anyoption
    url: anyoption.com
  - name: powerballs
    url: powerballs.si
  - name: finechance
    url: finechance.com
  - name: saunta
    url: saunta.com
  - name: javgals
    url: javgals.com
  - name: avflix
    url: avflix.tv
  - name: pspadik
    url: pspadik.com
  - name: pspadik
    url: pspadik.com
  - name: mcafee
    url: mcafee.com
  - name: happyd
    url: happyd.cn
  - name: da100
    url: da100.com
  - name: da1234
    url: da1234.cn
  - name: irip
    url: irip.com
  - name: irip
    url: irip.com
  - name: wvtaxsales
    url: wvtaxsales.com
  - name: omegawow
    url: omegawow.com
  - name: o2o1
    url: o2o1.com
  - name: komets
    url: komets.com
  - name: komets
    url: komets.com
  - name: wwwfox
    url: wwwfox.com
  - name: wwwfox
    url: wwwfox.com
  - name: kiwiindian
    url: kiwiindian.com
  - name: youtube
    url: youtube.com
  - name: porsche
    url: porsche.com
  - name: rivet
    url: rivet.com
  - name: wipro
    url: wipro.com
  - name: otzar
    url: otzar.biz
  - name: oracle
    url: oracle.com
  - name: mynewsize
    url: mynewsize.com
  - name: mynewsize
    url: mynewsize.com
  - name: coverups
    url: coverups.com
  - name: act
    url: act.uk.com
  - name: timetotrade
    url: timetotrade.eu
  - name: alexkale
    url: alexkale.co.uk
  - name: nolast
    url: nolast.com
  - name: nolast
    url: nolast.com
  - name: carlinha
    url: carlinha.org
  - name: mets
    url: mets.com
  - name: iml
    url: iml.es
  - name: itestcash
    url: itestcash.com
  - name: hardindd
    url: hardindd.com
  - name: minerals
    url: minerals.net
  - name: detonics
    url: detonics.com
  - name: zap
    url: zap.com.br
  - name: penisdicke
    url: penisdicke.de
  - name: penispedia
    url: penispedia.de
  - name: motoscustom
    url: motoscustom.es
  - name: subssearch
    url: subssearch.com
  - name: inoforum
    url: inoforum.ru
  - name: zdrente
    url: zdrente.com
  - name: zdrente
    url: zdrente.com
  - name: myanmarhoo
    url: myanmarhoo.com
  - name: Ojolink
    url: Ojolink.net
  - name: ojolink
    url: ojolink.net
  - name: ojolink
    url: ojolink.fr
  - name: juegosipo
    url: juegosipo.com
  - name: just-elle
    url: just-elle.com
  - name: myspace
    url: myspace.com
  - name: xjp
    url: xjp.cc
  - name: xnxx
    url: xnxx.com
  - name: fantasti
    url: fantasti.cc
  - name: youjizz
    url: youjizz.com
  - name: Wide6
    url: Wide6.com
  - name: wide6
    url: wide6.com
  - name: pornfuze
    url: pornfuze.com
  - name: porntitan
    url: porntitan.com
  - name: pornchilli
    url: pornchilli.com
  - name: 4tube
    url: 4tube.com
  - name: pornrabbit
    url: pornrabbit.com
  - name: eatbigbuns
    url: eatbigbuns.com
  - name: commencal
    url: commencal.com
  - name: harlotwear
    url: harlotwear.com
  - name: classnotes
    url: classnotes.com
  - name: classnotes
    url: classnotes.com
  - name: asgreenas
    url: asgreenas.com
  - name: asgreenas
    url: asgreenas.com
  - name: zshareblog
    url: zshareblog.com
  - name: Nasir
    url: Nasir.com
  - name: nasir
    url: nasir.com
  - name: gb13
    url: gb13.com
  - name: gb13
    url: gb13.com
  - name: pal-mafia
    url: pal-mafia.com
  - name: emu
    url: emu.edu
  - name: rapishare
    url: rapishare.com
  - name: rapishare
    url: rapishare.com
  - name: gadgethouse
    url: gadgethouse.nl
  - name: adult-mate
    url: adult-mate.com
  - name: clixsence
    url: clixsence.com
  - name: clixsence
    url: clixsence.com
  - name: mclub
    url: mclub.com.ua
  - name: higou
    url: higou.net
  - name: privatebay
    url: privatebay.com
  - name: frater
    url: frater.org
  - name: stork
    url: stork.pk
  - name: makelaar-nl
    url: makelaar-nl.nl
  - name: feest-idee
    url: feest-idee.nl
  - name: feest-start
    url: feest-start.nl
  - name: groepsfeest
    url: groepsfeest.nl
  - name: groepsfeest
    url: groepsfeest.nl
  - name: feestid
    url: feestid.nl
  - name: toptrips
    url: toptrips.com
  - name: letsgo
    url: letsgo.com
  - name: unp
    url: unp.com
  - name: isai
    url: isai.in
  - name: hwh
    url: hwh.com
  - name: babcock
    url: babcock.co.uk
  - name: watches
    url: watches.de
  - name: galaxygui
    url: galaxygui.net
  - name: digobrands
    url: digobrands.com
  - name: bgescape
    url: bgescape.com
  - name: scottdrake
    url: scottdrake.com
  - name: futera
    url: futera.com
  - name: strefa
    url: strefa.co.uk
  - name: axess
    url: axess.se
  - name: axess
    url: axess.se
  - name: ikarusc42
    url: ikarusc42.info
  - name: ds-girls
    url: ds-girls.nl
  - name: murocortina
    url: murocortina.es
  - name: diodosled
    url: diodosled.com
  - name: nacaranta
    url: nacaranta.com
  - name: uzboys
    url: uzboys.com
  - name: ripurl
    url: ripurl.co.uk
  - name: ripurl
    url: ripurl.co.uk
  - name: metroflog
    url: metroflog.com
  - name: iFight365
    url: iFight365.com
  - name: ifight365
    url: ifight365.com
  - name: simerini
    url: simerini.com
  - name: 4gifs
    url: 4gifs.com
  - name: tronix
    url: tronix.co.nz
  - name: torrentzap
    url: torrentzap.com
  - name: torrentzap
    url: torrentzap.com
  - name: wzforumz
    url: wzforumz.org
  - name: benjohnson
    url: benjohnson.com
  - name: lings
    url: lings.com
  - name: otrjobs
    url: otrjobs.net
  - name: fireeq
    url: fireeq.net
  - name: google
    url: google.com
  - name: live
    url: live.com
  - name: msn
    url: msn.com
  - name: wikipedia
    url: wikipedia.org
  - name: blogger
    url: blogger.com
  - name: baidu
    url: baidu.com
  - name: yahoo
    url: yahoo.co.jp
  - name: google
    url: google.co.in
  - name: google
    url: google.de
  - name: qq
    url: qq.com
  - name: microsoft
    url: microsoft.com
  - name: sina
    url: sina.com.cn
  - name: rapidshare
    url: rapidshare.com
  - name: google
    url: google.fr
  - name: wordpress
    url: wordpress.com
  - name: google
    url: google.co.uk
  - name: google
    url: google.cn
  - name: craigslist
    url: craigslist.org
  - name: ebay
    url: ebay.com
  - name: fc2
    url: fc2.com
  - name: google
    url: google.com.br
  - name: bing
    url: bing.com
  - name: yandex
    url: yandex.ru
  - name: yandex
    url: yandex.ru
  - name: vkontakte
    url: vkontakte.ru
  - name: mail
    url: mail.ru
  - name: google
    url: google.it
  - name: flickr
    url: flickr.com
  - name: google
    url: google.co.jp
  - name: amazon
    url: amazon.com
  - name: aol
    url: aol.com
  - name: hi5
    url: hi5.com
  - name: google
    url: google.es
  - name: taobao
    url: taobao.com
  - name: "163"
    url: 163.com
  - name: bbc
    url: bbc.co.uk
  - name: google
    url: google.com.mx
  - name: orkut
    url: orkut.com.br
  - name: go
    url: go.com
  - name: youporn
    url: youporn.com
  - name: vmn
    url: vmn.net
  - name: ask
    url: ask.com
  - name: pornhub
    url: pornhub.com
  - name: Skyrock
    url: Skyrock.com
  - name: skyrock
    url: skyrock.com
  - name: sohu
    url: sohu.com
  - name: conduit
    url: conduit.com
  - name: adobe
    url: adobe.com
  - name: apple
    url: apple.com
  - name: google
    url: google.ca
  - name: cnn
    url: cnn.com
  - name: megaupload
    url: megaupload.com
  - name: orkut
    url: orkut.co.in
  - name: imageshack
    url: imageshack.us
  - name: uol
    url: uol.com.br
  - name: google
    url: google.com.tr
  - name: youku
    url: youku.com
  - name: rakuten
    url: rakuten.co.jp
  - name: redtube
    url: redtube.com
  - name: ebay
    url: ebay.de
  - name: livejasmin
    url: livejasmin.com
  - name: cnet
    url: cnet.com
  - name: tube8
    url: tube8.com
  - name: ameblo
    url: ameblo.jp
  - name: rediff
    url: rediff.com
  - name: about
    url: about.com
  - name: soso
    url: soso.com
  - name: google
    url: google.co.id
  - name: livedoor
    url: livedoor.com


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upgraded-symmetrical-waddle
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Waddle
  introTitle: "**Waddle** is powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data. No server required — just GitHub Actions, Issues, and Pages.
  theme: ocean
  navbar:
    - title: Status
      href: /
    #- title: GitHub
    #  href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
i18n:
  footer: This page is  powered by [Waddle](https://giuseppefilingeri.github.io/upgraded-symmetrical-waddle/)
